######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 27 18:39:40 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
